// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Specflow.Steps.Db.Pg.Tests.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Microsoft.VisualStudio.TestTools.UnitTesting.TestClassAttribute()]
    public partial class DatabaseTestFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private Microsoft.VisualStudio.TestTools.UnitTesting.TestContext _testContext;
        
        private string[] _featureTags = ((string[])(null));
        
#line 1 "DatabaseTest.feature"
#line hidden
        
        public virtual Microsoft.VisualStudio.TestTools.UnitTesting.TestContext TestContext
        {
            get
            {
                return this._testContext;
            }
            set
            {
                this._testContext = value;
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassInitializeAttribute()]
        public static void FeatureSetup(Microsoft.VisualStudio.TestTools.UnitTesting.TestContext testContext)
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "DatabaseTest", "\tDemonstrates populating and asserting expected data in a SQL Server database", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.ClassCleanupAttribute()]
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestInitializeAttribute()]
        public virtual void TestInitialize()
        {
            if (((testRunner.FeatureContext != null) 
                        && (testRunner.FeatureContext.FeatureInfo.Title != "DatabaseTest")))
            {
                global::Specflow.Steps.Db.Pg.Tests.Features.DatabaseTestFeature.FeatureSetup(null);
            }
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestCleanupAttribute()]
        public virtual void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Microsoft.VisualStudio.TestTools.UnitTesting.TestContext>(_testContext);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        public virtual void FeatureBackground()
        {
#line 4
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "name",
                        "contact_name",
                        "contact_phone",
                        "contact_email"});
            table1.AddRow(new string[] {
                        "1",
                        "sup-1",
                        "cont-1",
                        "phone-1",
                        "email-1"});
            table1.AddRow(new string[] {
                        "2",
                        "sup-2",
                        "cont-2",
                        "phone-2",
                        "email-2"});
#line 5
testRunner.Given("table with identity columns \'public.supplier\' contains the data", ((string)(null)), table1, "Given ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "id",
                        "name"});
            table2.AddRow(new string[] {
                        "1",
                        "cat-1"});
            table2.AddRow(new string[] {
                        "2",
                        "cat-2"});
#line 9
testRunner.Given("table with identity columns \'public.category\' contains the data", ((string)(null)), table2, "Given ");
#line hidden
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Populate and validate a table")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DatabaseTest")]
        public virtual void PopulateAndValidateATable()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Populate and validate a table", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 14
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table3 = new TechTalk.SpecFlow.Table(new string[] {
                            "code",
                            "name",
                            "description",
                            "cost",
                            "list_price",
                            "category_id",
                            "supplier_id",
                            "is_active",
                            "release_date",
                            "created_on"});
                table3.AddRow(new string[] {
                            "code-1",
                            "product-1",
                            "[NULL]",
                            "101.10",
                            "111.10",
                            "1",
                            "2",
                            "1",
                            "2000-01-01",
                            "2000-02-01"});
                table3.AddRow(new string[] {
                            "code-2",
                            "product-2",
                            "desc-2",
                            "102.10",
                            "112.10",
                            "1",
                            "2",
                            "1",
                            "2000-01-02",
                            "2000-02-02"});
                table3.AddRow(new string[] {
                            "code-3",
                            "product-3",
                            "desc-3",
                            "103.10",
                            "113.10",
                            "2",
                            "1",
                            "1",
                            "2000-01-03",
                            "2000-02-03"});
                table3.AddRow(new string[] {
                            "code-4",
                            "product-4",
                            "",
                            "104.10",
                            "114.10",
                            "2",
                            "1",
                            "0",
                            "2000-01-04",
                            "2000-02-04"});
                table3.AddRow(new string[] {
                            "code-5",
                            "product-5",
                            "[NULL]",
                            "105.10",
                            "115.10",
                            "2",
                            "1",
                            "0",
                            "2000-01-05",
                            "2000-02-05"});
#line 15
testRunner.Given("table \'public.product\' contains the data", ((string)(null)), table3, "Given ");
#line hidden
#line 22
testRunner.When("I execute my operation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table4 = new TechTalk.SpecFlow.Table(new string[] {
                            "id:Key",
                            "code",
                            "name",
                            "description",
                            "cost:Number",
                            "list_price:Number",
                            "category_id",
                            "supplier_id",
                            "is_active:Boolean",
                            "release_date:DateTime",
                            "created_on:DateTime"});
                table4.AddRow(new string[] {
                            "101",
                            "code-1",
                            "product-1",
                            "[NULL]",
                            "101.10",
                            "111.10",
                            "1",
                            "2",
                            "true",
                            "2000-01-01",
                            "2000-02-01"});
                table4.AddRow(new string[] {
                            "102",
                            "code-2",
                            "product-2",
                            "desc-2",
                            "102.10",
                            "112.10",
                            "1",
                            "2",
                            "true",
                            "2000-01-02",
                            "2000-02-02"});
                table4.AddRow(new string[] {
                            "103",
                            "code-3",
                            "product-3",
                            "desc-3",
                            "103.10",
                            "113.10",
                            "2",
                            "1",
                            "true",
                            "2000-01-03",
                            "2000-02-03"});
                table4.AddRow(new string[] {
                            "104",
                            "code-4",
                            "product-4",
                            "",
                            "104.10",
                            "114.10",
                            "2",
                            "1",
                            "false",
                            "2000-01-04",
                            "2000-02-04"});
                table4.AddRow(new string[] {
                            "105",
                            "code-5",
                            "product-5",
                            "[NULL]",
                            "105.10",
                            "115.10",
                            "2",
                            "1",
                            "false",
                            "2000-01-05",
                            "2000-02-05"});
#line 23
testRunner.Then("table \'public.product\' should contain the data", ((string)(null)), table4, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Populate and validate a table with identity column")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DatabaseTest")]
        public virtual void PopulateAndValidateATableWithIdentityColumn()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Populate and validate a table with identity column", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 31
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table5 = new TechTalk.SpecFlow.Table(new string[] {
                            "id",
                            "code",
                            "name",
                            "description",
                            "cost",
                            "list_price",
                            "category_id",
                            "supplier_id",
                            "is_active",
                            "release_date",
                            "created_on"});
                table5.AddRow(new string[] {
                            "1",
                            "code-1",
                            "product-1",
                            "desc-1",
                            "101.10",
                            "111.10",
                            "1",
                            "2",
                            "1",
                            "2000-01-01",
                            "2000-02-01"});
                table5.AddRow(new string[] {
                            "2",
                            "code-2",
                            "product-2",
                            "desc-2",
                            "102.10",
                            "112.10",
                            "1",
                            "2",
                            "1",
                            "2000-01-02",
                            "2000-02-02"});
                table5.AddRow(new string[] {
                            "3",
                            "code-3",
                            "product-3",
                            "desc-3",
                            "103.10",
                            "113.10",
                            "2",
                            "1",
                            "1",
                            "2000-01-03",
                            "2000-02-03"});
                table5.AddRow(new string[] {
                            "4",
                            "code-4",
                            "product-4",
                            "",
                            "104.10",
                            "114.10",
                            "2",
                            "1",
                            "0",
                            "2000-01-04",
                            "2000-02-04"});
                table5.AddRow(new string[] {
                            "5",
                            "code-5",
                            "product-5",
                            "[NULL]",
                            "105.10",
                            "115.10",
                            "2",
                            "1",
                            "0",
                            "2000-01-05",
                            "2000-02-05"});
#line 32
testRunner.Given("table with identity columns \'public.product\' contains the data", ((string)(null)), table5, "Given ");
#line hidden
#line 39
testRunner.When("I execute my operation", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
                TechTalk.SpecFlow.Table table6 = new TechTalk.SpecFlow.Table(new string[] {
                            "id:Key",
                            "code",
                            "name",
                            "description",
                            "cost:Number",
                            "list_price:Number",
                            "category_id",
                            "supplier_id",
                            "is_active:Boolean",
                            "release_date:DateTime"});
                table6.AddRow(new string[] {
                            "1",
                            "code-1",
                            "product-1",
                            "desc-1",
                            "101.10",
                            "111.10",
                            "1",
                            "2",
                            "true",
                            "2000-01-01"});
                table6.AddRow(new string[] {
                            "2",
                            "code-2",
                            "product-2",
                            "desc-2",
                            "102.10",
                            "112.10",
                            "1",
                            "2",
                            "true",
                            "2000-01-02"});
                table6.AddRow(new string[] {
                            "3",
                            "code-3",
                            "product-3",
                            "desc-3",
                            "103.10",
                            "113.10",
                            "2",
                            "1",
                            "true",
                            "2000-01-03"});
                table6.AddRow(new string[] {
                            "4",
                            "code-4",
                            "product-4",
                            "",
                            "104.10",
                            "114.10",
                            "2",
                            "1",
                            "false",
                            "2000-01-04"});
                table6.AddRow(new string[] {
                            "5",
                            "code-5",
                            "product-5",
                            "[NULL]",
                            "105.10",
                            "115.10",
                            "2",
                            "1",
                            "false",
                            "2000-01-05"});
#line 40
testRunner.Then("table \'public.product\' should contain the data", ((string)(null)), table6, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Filter and validate a table - one field, one value")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DatabaseTest")]
        public virtual void FilterAndValidateATable_OneFieldOneValue()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Filter and validate a table - one field, one value", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 48
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table7 = new TechTalk.SpecFlow.Table(new string[] {
                            "id",
                            "code",
                            "name",
                            "description",
                            "cost",
                            "list_price",
                            "category_id",
                            "supplier_id",
                            "is_active",
                            "release_date",
                            "created_on"});
                table7.AddRow(new string[] {
                            "1",
                            "code-1",
                            "product-1",
                            "desc-1",
                            "101.10",
                            "111.10",
                            "1",
                            "2",
                            "1",
                            "2000-01-01",
                            "2000-02-01"});
                table7.AddRow(new string[] {
                            "2",
                            "code-2",
                            "product-2",
                            "desc-2",
                            "102.10",
                            "112.10",
                            "1",
                            "2",
                            "1",
                            "2000-01-02",
                            "2000-02-02"});
                table7.AddRow(new string[] {
                            "3",
                            "code-3",
                            "product-3",
                            "desc-3",
                            "103.10",
                            "113.10",
                            "2",
                            "1",
                            "1",
                            "2000-01-03",
                            "2000-02-03"});
                table7.AddRow(new string[] {
                            "4",
                            "code-4",
                            "product-4",
                            "",
                            "104.10",
                            "114.10",
                            "2",
                            "1",
                            "0",
                            "2000-01-04",
                            "2000-02-04"});
                table7.AddRow(new string[] {
                            "5",
                            "code-5",
                            "product-5",
                            "[NULL]",
                            "105.10",
                            "115.10",
                            "2",
                            "1",
                            "0",
                            "2000-01-05",
                            "2000-02-05"});
#line 49
testRunner.Given("table with identity columns \'public.product\' contains the data", ((string)(null)), table7, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table8 = new TechTalk.SpecFlow.Table(new string[] {
                            "FieldName",
                            "FieldValues"});
                table8.AddRow(new string[] {
                            "id",
                            "2"});
#line 56
testRunner.Given("I filter table \'public.product\' by", ((string)(null)), table8, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table9 = new TechTalk.SpecFlow.Table(new string[] {
                            "id:Key",
                            "code",
                            "name",
                            "description",
                            "cost:Number",
                            "list_price:Number",
                            "category_id",
                            "supplier_id",
                            "is_active:Boolean",
                            "release_date:DateTime"});
                table9.AddRow(new string[] {
                            "2",
                            "code-2",
                            "product-2",
                            "desc-2",
                            "102.10",
                            "112.10",
                            "1",
                            "2",
                            "true",
                            "2000-01-02"});
#line 59
testRunner.Then("table \'public.product\' should contain the data", ((string)(null)), table9, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Filter and validate a table - multiple fields and values")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DatabaseTest")]
        public virtual void FilterAndValidateATable_MultipleFieldsAndValues()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Filter and validate a table - multiple fields and values", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 63
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table10 = new TechTalk.SpecFlow.Table(new string[] {
                            "id",
                            "code",
                            "name",
                            "description",
                            "cost",
                            "list_price",
                            "category_id",
                            "supplier_id",
                            "is_active",
                            "release_date",
                            "created_on"});
                table10.AddRow(new string[] {
                            "1",
                            "code-1",
                            "product-1",
                            "desc-1",
                            "101.10",
                            "111.10",
                            "1",
                            "2",
                            "1",
                            "2000-01-01",
                            "2000-02-01"});
                table10.AddRow(new string[] {
                            "2",
                            "code-2",
                            "product-2",
                            "desc-2",
                            "102.10",
                            "112.10",
                            "1",
                            "2",
                            "1",
                            "2000-01-02",
                            "2000-02-02"});
                table10.AddRow(new string[] {
                            "3",
                            "code-3",
                            "product-3",
                            "desc-3",
                            "103.10",
                            "113.10",
                            "2",
                            "1",
                            "1",
                            "2000-01-03",
                            "2000-02-03"});
                table10.AddRow(new string[] {
                            "4",
                            "code-4",
                            "product-4",
                            "",
                            "104.10",
                            "114.10",
                            "2",
                            "1",
                            "0",
                            "2000-01-04",
                            "2000-02-04"});
                table10.AddRow(new string[] {
                            "5",
                            "code-5",
                            "product-5",
                            "[NULL]",
                            "105.10",
                            "115.10",
                            "2",
                            "1",
                            "0",
                            "2000-01-05",
                            "2000-02-05"});
#line 64
testRunner.Given("table with identity columns \'public.product\' contains the data", ((string)(null)), table10, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table11 = new TechTalk.SpecFlow.Table(new string[] {
                            "FieldName",
                            "FieldValues"});
                table11.AddRow(new string[] {
                            "id",
                            "1,2,5"});
                table11.AddRow(new string[] {
                            "is_active",
                            "1"});
#line 71
testRunner.Given("I filter table \'public.product\' by", ((string)(null)), table11, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table12 = new TechTalk.SpecFlow.Table(new string[] {
                            "id:Key",
                            "code",
                            "name",
                            "description",
                            "cost:Number",
                            "list_price:Number",
                            "category_id",
                            "supplier_id",
                            "is_active:Boolean",
                            "release_date:DateTime"});
                table12.AddRow(new string[] {
                            "1",
                            "code-1",
                            "product-1",
                            "desc-1",
                            "101.10",
                            "111.10",
                            "1",
                            "2",
                            "true",
                            "2000-01-01"});
                table12.AddRow(new string[] {
                            "2",
                            "code-2",
                            "product-2",
                            "desc-2",
                            "102.10",
                            "112.10",
                            "1",
                            "2",
                            "true",
                            "2000-01-02"});
#line 75
testRunner.Then("table \'public.product\' should contain the data", ((string)(null)), table12, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Filter and validate multiple tables")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DatabaseTest")]
        public virtual void FilterAndValidateMultipleTables()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Filter and validate multiple tables", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 80
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table13 = new TechTalk.SpecFlow.Table(new string[] {
                            "FieldName",
                            "FieldValues"});
                table13.AddRow(new string[] {
                            "name",
                            "sup-1"});
#line 81
testRunner.Given("I filter table \'public.supplier\' by", ((string)(null)), table13, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table14 = new TechTalk.SpecFlow.Table(new string[] {
                            "FieldName",
                            "FieldValues"});
                table14.AddRow(new string[] {
                            "name",
                            "cat-2"});
#line 84
testRunner.Given("I filter table \'public.category\' by", ((string)(null)), table14, "Given ");
#line hidden
                TechTalk.SpecFlow.Table table15 = new TechTalk.SpecFlow.Table(new string[] {
                            "id",
                            "name",
                            "contact_name",
                            "contact_phone",
                            "contact_email"});
                table15.AddRow(new string[] {
                            "1",
                            "sup-1",
                            "cont-1",
                            "phone-1",
                            "email-1"});
#line 87
testRunner.Then("table \'public.supplier\' should contain the data", ((string)(null)), table15, "Then ");
#line hidden
                TechTalk.SpecFlow.Table table16 = new TechTalk.SpecFlow.Table(new string[] {
                            "id",
                            "name"});
                table16.AddRow(new string[] {
                            "2",
                            "cat-2"});
#line 90
testRunner.Then("table \'public.category\' should contain the data", ((string)(null)), table16, "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestMethodAttribute()]
        [Microsoft.VisualStudio.TestTools.UnitTesting.DescriptionAttribute("Validate empty table")]
        [Microsoft.VisualStudio.TestTools.UnitTesting.TestPropertyAttribute("FeatureTitle", "DatabaseTest")]
        public virtual void ValidateEmptyTable()
        {
            string[] tagsOfScenario = ((string[])(null));
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Validate empty table", null, tagsOfScenario, argumentsOfScenario, this._featureTags);
#line 94
this.ScenarioInitialize(scenarioInfo);
#line hidden
            bool isScenarioIgnored = default(bool);
            bool isFeatureIgnored = default(bool);
            if ((tagsOfScenario != null))
            {
                isScenarioIgnored = tagsOfScenario.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((this._featureTags != null))
            {
                isFeatureIgnored = this._featureTags.Where(__entry => __entry != null).Where(__entry => String.Equals(__entry, "ignore", StringComparison.CurrentCultureIgnoreCase)).Any();
            }
            if ((isScenarioIgnored || isFeatureIgnored))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 4
this.FeatureBackground();
#line hidden
                TechTalk.SpecFlow.Table table17 = new TechTalk.SpecFlow.Table(new string[] {
                            "FieldName",
                            "FieldValues"});
                table17.AddRow(new string[] {
                            "name",
                            "sup-10"});
#line 95
testRunner.Given("I filter table \'public.supplier\' by", ((string)(null)), table17, "Given ");
#line hidden
#line 98
testRunner.Then("table \'public.supplier\' should be empty", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
